[project]
name = "vision-finetune"
version = "0.1.0"
description = "Fine-tuning Vision Language Models (VLMs)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.1",
    "bitsandbytes>=0.47.0",
    "hf-transfer>=0.1.9",
    "ninja>=1.13.0",
    "peft>=0.17.1",
    "progrich>=0.2.0",
    "rich>=14.1.0",
    "simple-parsing>=0.1.7",
    "torchvision>=0.23.0",
    "transformers>=4.56.2",
    "trl>=0.23.0",
    "unsloth",
    "wandb>=0.22.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.31.5",
    "debugpy>=1.8.17",
    "pybind11>=2.13.6",
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]
triton = [
  "triton>=3.4.0",
]
full = [
  {include-group = "triton"},
  "xformers>=0.0.32",
  "unsloth-zoo",
  # This is here and not above, because on arm64 in order to install compile triton you need PyTorch, but PyTorch itself
  # depends on triton, hence it wouldn't work. But if PyTorch is not specified when compiling triton, it uses the CPU
  # only version, which does not depend on triton. Sounds odd, but the custom registry only applies to direct
  # dependencies, not their dependencies.
  "torch>=2.8.0",
]

[tool.basedpyright]
typeCheckingMode = "standard"
reportPrivateImportUsage = false
reportMatchNotExhaustive = true
reportUnnecessaryComparison = true
# These need to be ignored separately, even though they are already in gitignore.
# Otherwise it tries to check all files in the virtual environment (.venv) or any
# of these generated directories.
exclude = [
  "**/__pycache__",
  ".ruff_cache/",
  ".cache/",
  ".venv/",
  "build",
  "log/",
  "unsloth_compiled_cache/",
]
# Automatically look in the virtual environment for packages
venv = ".venv"
venvPath = "."


[tool.pytest.ini_options]
testpaths = "test"

[tool.ruff.lint]
# Additionally include import sorting lints (and automatic formatting with --fix)
extend-select = ["I"]

[tool.uv]
no-build-isolation-package = ["triton", "xformers"]
default-groups = ["dev", "full"]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "platform_machine == 'aarch64'" },
]
torchvision = [
  { index = "pytorch-cu126", marker = "platform_machine == 'aarch64'" },
]
triton = { git = "https://github.com/triton-lang/triton", subdirectory = "python", branch = "release/3.2.x", marker = "platform_machine == 'aarch64'" }
unsloth = { git = "https://github.com/unslothai/unsloth.git" }
unsloth-zoo = { git = "https://github.com/unslothai/unsloth-zoo.git" }
xformers = { git = "https://github.com/facebookresearch/xformers", tag = "v0.0.29.post3", marker = "platform_machine == 'aarch64'" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

# This looks very unnecessary and noisy, but because these are built from source on aarch64,
# they are not installed by default, but uv still needs to know the build dependencies of them.
[[tool.uv.dependency-metadata]]
name = "triton"
requires-dist = ["setuptools", "pybind11"]

[[tool.uv.dependency-metadata]]
name = "xformers"
requires-dist = ["setuptools", "torch"]
